version: "3"
services:  
    mongo:
        image: mongo:4.4.1 # Instead of build you can use 'image: mongo'
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWD
            MONGO_INITDB_DATABASE: dbuser
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            # - mongo-volume:/data/db  
    backend:   
        image: officialalikhani/ssh_api:0.1-0-0
        container_name: api
        restart: always
        ports:
            - 6655:3838
            - 2222:22
        environment:
            ENVPORT: 3838
            ENVMONGOPASS: mongo_password
    web:
        build: 
            context: ../Hyper-admin-panel/
            dockerfile: Dockerfile
        container_name: web
        restart: always
        ports:
            - 8081:3000
# volumes:
#   mongo-volume: